### PR TITLE
Open logout link in same window instead of a new tab

### LINKED ISSUE #51: Logout not working
Hi,

The Logout button in the hub menu opens a new tab with the login page, but it doesn't logout the user. I have to switch from /lab to /tree in the url as commented in #40 to do the trick.

I have Jupyterhub running with a sudo user and using SudoSpawner. I had to set "hub_prefix" to "/hub" following #50 to get the "Hub" menu.
```bash
jupyter --version
4.4.0
jupyterhub --version
0.8.1

jupyter labextension list
JupyterLab v0.31.12
Known labextensions:
   app dir: /usr/local/share/jupyter/lab
@jupyterlab/hub-extension
        @jupyterlab/hub-extension v0.8.1  enabled  OK
```
I have no experience with node and npm, could it be something related to a node package?
I get some warnings when running the command ```sudo jupyter labextension install @jupyterlab/hub-extension``` because of the react version. I have installed react@15.6.2 as global and linked in the user account. Tried to force install of react 15.0.0 but keeps installing the latest version.
```bash
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has unmet peer dependency "react@^15.6.1".
warning "@jupyterlab/json-extension > react-highlighter@0.4.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react-dom@^15.0.0".
```

Is it something known, the react version or am I missing something?

Thank you!

### PR DESCRIPTION
**Pull request by betatim**
Users are confused that they are "logged but not" because the logout link opens in a new tab and the JupyterLab view they have in the other tab appears to still work.

This changes the menu item so that it navigates to the logout URL like the notebook interface does when you press the logout button on JupyterHub.

Closes #51 #48

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -67,7 +67,7 @@ function activateHubExtension(app: JupyterLab, palette: ICommandPalette, mainMen
     label: 'Logout',
     caption: 'Log out of the Hub',
     execute: () => {
-      window.open(hubHost + URLExt.join(hubPrefix, 'logout'), '_blank');
+      window.location.href = hubHost + URLExt.join(hubPrefix, 'logout');
```
Comment (betatim) [inline src/index.ts]: This seems to be the "recommended" way to navigate to a new page in the same window. I don't know enough JS to really know, so if someone does let me know.

**Comment by betatim** [comment]
This change was brought to you by the good people from https://www.hdfgroup.org/
